### ISSUE TITLE
Unrelated question Darius

### ISSUE THREAD

**Issue by CaptainCodeAU** [chitoroagad/advent_of_code_24#1]
Hi Darius,

Sorry I couldn't find your contact info anywhere so reaching out this way. 

By the way, congratulations for winning UCL x ICL Hackathon! Well done!

I have a quick question regarding that project "Meta-Ray-Ban_sign-language-translate" - HOW exactly did you stream the Meta glasses video to your computer? I'm working on a project where I need to transfer the images from the Meta glasses, straight to my computer. I'm wondering if I have to go down to the packet level or if there is another route that I'm not aware of.

Any help would be greatly appreciated.

Thanks
Gav

**Comment by chitoroagad** [comment]
Hi Gav,

Thanks!
In the spirit of the hackathon we came up with a very hacky solution to your problem. 
The only way you can stream video from the glasses is by streaming to Instagram or Facebook directly. So we streamed to Facebook and used OBS to create a virtual display which could be accessed by OpenCV. 
so in the end it ended up being a ~10s delay before we could actually process any video from the glasses. 

Hope this helps,
Darius

**Comment by CaptainCodeAU** [comment]
Thanks so much for your reply, Darius. It looks like you used the same approach as the Harvard students. Hopefully, someone will figure out how to read the packets, thereby reducing the hops.

Thanks again.
